### ISSUE TITLE
Onyx The Black Cat?

### ISSUE THREAD

**Issue by ylluminate** [flagersgit/NotSoPrivate#1]
How does this compare to Onyx The Black Cat? I've had some strange hangs and so forth that Apple can't seem to help with and it seems that I can't see sufficient system information about the hangs with `dtrace` and other mechanisms without relaxing things a bit further.

**Comment by flagersgit** [comment]
The purpose of the project is just to unredact logs which have had their format strings replaced with `<private>` on OSes with the unified logging system. Currently, it is broken on Big Sur+ as those OSes no longer use the commpage to check if private logging is enabled.

**Comment by ylluminate** [comment]
Hmmm, that's really unfortunate because this seems to carry through in other areas such as dtrace, etc. as well. Even thought this doesn't work for general logging, can it be used for non-Console.app logs with similarly?
